### ISSUE TITLE
Quick Sort in cpp 

### ISSUE THREAD

**Issue by Ayush0431** [Ayush0431/Data-structure-algoritms-hacktoberfest#29]

**Comment by deja-v** [comment]
please assign me this issue @Ayush0431

**Comment by SD-softuser** [comment]
please assign me @Ayush0431

**Comment by Shamik1836** [comment]
I want to work on this issue, can you kindly assign this to me?

**Comment by anupeshverma** [comment]
!assign

**Comment by anupeshverma** [comment]
assign it to me

**Comment by Ayush0431** [comment]
> please assign me this issue @Ayush0431

Done , go ahead !!!!
